future is not used by graphite2 package
--- graphite2-1.3.14/setup.py.orig	2020-04-01 04:53:13.000000000 +0200
+++ graphite2-1.3.14/setup.py	2020-05-07 20:21:02.267362656 +0200
@@ -26,7 +26,6 @@
     zip_safe         = False,
     package_dir      = {'': 'python'},
     packages         = ['graphite2'],
-    install_requires = ['future'],
     long_description = long_description,
     long_description_content_type = 'text/markdown',
     classifiers = [
